---
name: Publish
on:
  workflow_dispatch:
    inputs:
      suffix:
        description: 'Release suffix'
        required: true

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Initialize Actions
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: dotnet publish
        run: "dotnet publish -c Release"
      - name: Archive the release
        uses: thedoctor0/zip-release@main
        with:
          type: zip
          directory: bin/Release/net6.0/win-x64/publish
          filename: targz-helper-${{ inputs.suffix }}.zip
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: bin/Release/net6.0/win-x64/publish/targz-helper-${{ inputs.suffix }}.zip
          tag: ${{ inputs.suffix }}
